#!/bin/bash
################
#
#About : Check user
#       permissions of
#        github repo members
#
#Date : 02/04/2024
#Author : Siyaram
#Version: v1
#
#################

set -x
helper()

#GitHub api url
api_url="https://api.github.com/devops-projects-practice"

#Github username and personal access token

USERNAME=$username
TOKEN=$token

#User and Rep info

REPO_OWNER=$1
REPO_NAME=$2

#Function to make a GET request to the GitHub api

functon github_api_get{
        local endpoint="$1"
        local url="${api_url}/${endpoint}"

        #Send a GET request to the Github ai with authentication
        curl -s -u "${USERNAME}":${TOKEN}" "${url}"


}

#Function to list users with read access to the repository

function list_users_with_read_access{

        local endpoint="repos/${REPO_OWNER}/${REPO_NAME}/collaborators"

#Fetch the list of collaborators on the repository

collaborators="$(github_api_get "$endpoint" | jq -r '.[] | select(.permissions.pull == true) | .login')"

        #Display the list of collaborators with read access

        if [[ -z "$collaborators" ]];then
                echo "No users with read access found for ${REPO_OWNER}/${REPO_NAME}."
        else
                echo"Users with read access to  :${REPO_OWNER}/${REPO_NAME} are :"
                echo"$collaborators"
        fi
}


function helper{
        local no_of_args=2
        if[ $# -ne $no_of_args];then
                echo" Please execute the script with correct arguements"
                echo"asd"
}

#Main Script--------

echo "Listing users with read access to ${REPO_NAME}/${REPO_OWNER}..."

list_users_with_read_access()

